apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello2-app-wortner
    release: my-prom
  name: hello2-app-wortner
spec:
  selector:
    app: hello2-app-wortner
    release: my-prom
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
    name: http