apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello2-app-wortner-service-monitor1
  labels:
    release: my-prom
    app: hello2-app-wortner
spec:
  endpoints:
  - port: http
    path: '/metrics'
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: hello2-app-wortner 
      release: my-prom
